plugins {
	id 'fabric-loom' version '1.6-SNAPSHOT'
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		url = "https://cursemaven.com"
	}

	maven {
		name = "Modrinth"
		url = "https://api.modrinth.com/maven"
	}

	maven {
		url = "https://maven.kyrptonaught.dev"
	}

	maven {
		url = "https://maven.repository.redhat.com/ga/"
	}

	maven {
		url = "https://s01.oss.sonatype.org/content/repositories/snapshots"
	}

	flatDir {
		dirs 'libs'
	}
}

loom {
    splitEnvironmentSourceSets()

	mods {
		"mtwmod" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}

	accessWidenerPath = file("src/main/resources/mtwmod.accesswidener")
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	var modrinthList = List.of(
			project.modmenu_version,
			project.voicechat_version,
			project.axiom_version,
			project.command_macros_version,
			project.pehkui_version
	)

	for (String mod : modrinthList) {
		modImplementation "maven.modrinth:$mod"
	}

	modImplementation "dev.mtwmod:mtwmod-resource:1.0.2"
	include modImplementation("dev.mtwmod:mtwmod-skinpreset:1.0.1")
	include modImplementation("dev.mtwmod:mtwmod-animation:1.0.0")
	include modImplementation("dev.mtwmod:better-third-person:1.0.0")
	modApi "dev.mtwmod:kyrptconfig:1.6.0-1.20.6"
//	modApi "maven.modrinth:rrls:Ip08v0S2"
//	modImplementation "dev.mtwmod:improved-animations:1.0.2"

	implementation "dnsjava:dnsjava:3.5.3"
	implementation "dev.mtwmod:terminalconsoleappender:1.4.0"
	implementation "org.jline:jline:3.25.1"

//	var ultralight_version = '0.0.2-SNAPSHOT'
//
//	include implementation("net.janrupf.ultralight:ultralight-java-reborn-core:$ultralight_version")
//	var ultralight_jni = "net.janrupf.ultralight:ultralight-java-reborn-platform-jni:$ultralight_version"
//	include implementation(ultralight_jni)

//	for (String arch : ["linux-x64", "win-x64", "mac-x64"]) {
//		implementation "$ultralight_jni:$arch"
//	}
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}