# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.16.9

# Mod Properties
mod_version = 1.15.2
maven_group = dev.magyul
archives_base_name = mtwmod

# Dependencies
fabric_version=0.92.2+1.20.1
modmenu_version = modmenu:7.2.2
voicechat_version = simple-voice-chat:fabric-1.20.1-2.5.26
pehkui_version = pehkui:3.8.3+1.14.4-1.21
command_block_ide_version = command-block-ide:0.4.4
command_macros_version = command-macros:1.6.3-1.20
axiom_version = axiom:4.1.1
better_fabric_console_version = better-fabric-console:1.1.6
modernkeybinding_verson = modernkeybinding:1.20.X-1.2.0
better_third_person_version = better-third-person:1yJzEpzh