# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.3
loader_version=0.15.11

# Mod Properties
mod_version = 1.13.3
maven_group = dev.magyul
archives_base_name = mtwmod

# Dependencies
fabric_version=0.100.4+1.20.6
modmenu_version = modmenu:10.0.0
voicechat_version = simple-voice-chat:fabric-1.20.6-2.5.18
pehkui_version = pehkui:3.8.3+1.14.4-1.21
command_block_ide_version = command-block-ide:0.4.7
command_macros_version = command-macros:1.6.3-1.20.4
axiom_version = axiom:sJP1pto6