# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.6
yarn_mappings=1.20.6+build.1
loader_version=0.15.11

# Mod Properties
mod_version = 1.12.6
maven_group = dev.magyul
archives_base_name = mtwmod

# Dependencies
fabric_version=0.97.8+1.20.6
modmenu_version = modmenu:10.0.0-beta.1
voicechat_version = simple-voice-chat:fabric-1.20.6-2.5.14
pehkui_version = pehkui:3.7.12+1.14.4-1.20.4
command_block_ide_version = command-block-ide:0.4.6
command_macros_version = command-macros:1.6.3-1.20.4
axiom_version = axiom:JMpH3gnj